- src/plugin.js
Verified on Chrome, Safari, Firefox, Edge, and Android Chrome
> fix: use player resize/fullscreenchange events which are more consistent

- index.html
- src/plugin.js
* Debugging was a pain without access to all the currently private variables
* Some of the variables need to be accessed again when we change videos
fix: switching a source should not create two canvases
fix: loading via player.src and video element source should work
fix: switching between 360 and non-360 sources with AUTO should work Fixes #8 
fix: allow Sphere/Cube as mediainfo projections
> feat: expose more of vrs methods

- src/plugin.js
For example, firefox 55 on win 10 with a Vive.
This addresses #14 as well.
> fix: add a cardboard button for native webvr support

- src/plugin.js
the orbit controls default configuration is not fit for the current use in the VR viewer : 
- rotation control seems inverted, as we are inside the sphere we control
- rotation control is too fast
- zoom and pan are enabled and if used will disrupt the viewing experience at mininum, eventually leading to getting out of the render sphere
so I added some configuration right after the OrbitControls instance creation
I also set the rendering of the sphere as one sided, rendering on the outside was useless
> Orbit controls configuration

- iframe.html
- index.html
- package-lock.json
- package.json
- src/plugin.js
- test/index.html
This is currently broken in every version of videojs-vr and webvr-polyfill < `0.10.2`
See: https://github.com/immersive-web/webvr-polyfill/issues/307
I also:
* exported vr on window for the test page
* added an iframe
* exported the polyfill version in a function
* and fixed karma-qunit, which is currently broken in master
> fix: chrome m55 android gyro breakage by updating webvr-polyfill

- src/plugin.js
Proposed solution for #66
- Move instantiating webvr-polyfill after IE check
- Trigger `web-vr-not-supported` error on `loadstart` — triggering the error earlier would result in the error overlay being hidden upon `loadstart` (videoJS resets error on `loadstart`)
-  Do not pass <a> tags in message to player.error() as it doesn't parse HTML markup
> fix: 'no 360 support' error in IE

- README.md
- index.html
- src/plugin.js
Previous Safari bugs with HLS/cors have been fixed and we can use the video texture again!
I also found an issue with the debug logger and multiple arguments, that has been fixed as well.
> fix: remove safari video image canvas work-around

- src/plugin.js
On initially going into cardboard mode on a device there would be instructions shown, but these instructions would not actually go away. This PR removes them.
Fixes #73 
* The cardboard mode button should still work on
> fix: do not show rotate instructions

- scripts/rollup-replace.js
- src/orbit-orientation-controls.js
- src/plugin.js
Recently `webvr-polyfill` removed support for the touch panner controls that they used to add to their polyfill vr headset. This PR brings them back. 
* Make sure that the latest versions of every browser can move around the video with touch controls or mouse
* Make sure that mobile browsers can move around the video by physically moving the phone:
> fix: implement touch pan controls again

- scripts/rollup-replace.js
- src/canvas-player-controls.js
- src/plugin.js
Fixes #92
Right now its now a lot of the default player behaviors are overridden by the other controls. This pr brings them back and makes them work how we would expect.
1. A click/tap with no movement (ie not moving around the scene) should toggle playback
2. When moving around the scene the control bar should not come up. It should only come up when playback is toggled or the control bar is moved over/clicked.
3. The context menu from `right click` should show up.
> fix: player controls

- src/cardboard-button.js
Proposed solution for #103 
- I believe `resize` event shouldn't be triggered on VR cardboard display deactivation. If this event is triggered, the canvas size needs to be reset to its original width/height manually since webvr-polyfill sets the canvas to 100x101px to address some of the Webkit specific issues.
> fix: ios sizing issue when deactivating vr cardboard display

- src/plugin.js
We add these listeners with `true` so we must remove them with `true`, or else nothing will happen.
Reported in #8 
See the docs here:`useCaption` on https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/removeEventListener
> fix: reset event listeners on window correctly

- README.md
- src/plugin.js
Add an option for motion controls to be turned off
Closes #127
> feat: motion controls option

- README.md
JavaScript code block syntax are not highlighted
Fix README.md JavaScript code block highlight
> Fix JavaScript highlight in README.md

- src/plugin.js
Trigger an initialization event when the three.js objects are available. It is helpful for someone who wants to add 3D objects in the video.
add videojs custom event trigger at the end of `init()` function
> custom event for vr initialization

- examples/180.html
- index.html
- src/orbit-orientation-controls.js
- src/plugin.js
- src/utils.js
Reference to #36 
Added support for 180Vr video as an enhancement.
- Updated the `plugin.js` by adding a condition if the projection equals 180 and added the logic to map the texture of the video to it.
- Added condition for `orbit-orientation-controls.js` to limit minimum and maximum rotation if the projection is half of the view
- Added 180 to the `validProjections` array in the `utils.js` file
- Added example page `180.html`
- `Index.html` updated with a link to 180 example page
- Added a 180 Vr sample video in the samples folder
> add 180 projection

- src/plugin.js
The `http-streaming` switches VR video to the lowest resolution available in HLS manifest after loading 1 
HLS chunk on HLS 360 video.
The problem is related to `http-streaming` and adaptive algorithm. The adaptive login will only work correctly when video tag has a width and height but the VR plugin sets `display: none` on `video` tag element which makes video tag width and height equal to 0.
We should use `opacity: 0` instead of `display: none` and insert canvas element after the video tag element to make it clickable.
> fix: VR switches to the lowest resolution after loading 1 HLS chunk on HLS 360 video

- src/canvas-player-controls.js
Fix different behavior between standard and vr360 player in iOS/Android devices
> Fix/ VR360 player's behavior different to standar player on mobile devices

- README.md
- examples/180-mono.html
- index.html
- package.json
- src/plugin.js
- src/utils.js
VR180 monoscopic is cropped
Enhancement
Adding new projection 180_MONO
Adding also 180_LR which is what the 180 projection is really doing, vs 180_TB
Future idea "180" could auto detect square input for example and choose 180_MONO
> Fixes #226

- CHANGELOG.md
- README.md
- scripts/rollup.config.js
- src/canvas-player-controls.js
- src/cardboard-button.js
- src/plugin.js
Fix some typos
Just some comments
> Correct some typos

- scripts/rollup-example-resolver.js
- scripts/rollup.config.js
Fixes #188
Issue #188 describes an issue where using the module build (`videojs-vr.es.js`) will break with the error `THREE is not defined`.  This is because the three.js example files are not bundled and so module consumers receive the unchanged version when installing three.js from npm.
This PR adds a custom resolver which will resolve the three.js example files and mark them as non-external.  This matches the output from the commonjs  bundle where the examples are part of the output  bundle and thus the changes from rollup replace  are preserved.
> Bundle three.js examples in module build

- README.md
- src/plugin.js
Currently the lack of detail in the underlying sphere mesh used in
equirectangular projections is very obvious and can cause visual
artifacts (a kind of wobble), especially noticeable at the poles.
See below:
Allow end user to increase the detail level of the sphere mesh.
> Add option for detail level in projection sphere

- package-lock.json
- package.json
- src/plugin.js
**NOTE:** BREAKING CHANGE!
This updates the default [browserslist](https://github.com/videojs/babel-config/blob/main/es.js#L6-L19) used by babel. It drops support for some older browsers including IE 11. This also removes the browserslist in package.json so we use the default list from @videojs/babel-config (linked above).
> chore: update build tooling to drop older browser support

- README.md
Netlify updated its default site URLs in 2020, transitioning from site-name.netlify.com to site-name.netlify.app.
(see https://answers.netlify.com/t/changes-coming-to-netlify-site-urls-com-to-app/8918)
In theory, the current demo link should still work via redirection. However, the link https://videojs-vr.netlify.com does not properly redirect to https://videojs-vr.netlify.app.
Updates the demo link in the readme to the correct .app URL to prevent confusion and ensure proper functionality.
> docs: update readme links from .com to .app
